#!/bin/bash

#sudo cp /usr/lib/emscripten/.emscripten /usr/lib/emsdk/.emscripten

if [ ! -d "src" ] 
then
    echo "Downloading mupdf"
    VERSION=1.20.0
    curl -s https://mupdf.com/downloads/archive/mupdf-$VERSION-source.tar.gz | tar -xz
    mv mupdf-$VERSION-source src
    cp src/COPYING LICENSE
    cp src/COPYING ../web/out/wasm/libmupdf.LICENSE
fi

cp -rT mod src

echo "Making"
make

echo "Copying"
mv libmupdf.js ../web/src/pdf/libmupdf.js
mv libmupdf.wasm ../web/out/wasm/libmupdf.wasm