name: Build and Deploy

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: web

      - name: Build
        run: npm run build
        working-directory: web

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.2
        with:
          branch: gh-pages
          folder: web/out
